[2023-07-11T22:02:46.620+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_users.spark_etl_users manual__2023-07-11T21:57:11.039797+00:00 [queued]>
[2023-07-11T22:02:46.627+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_users.spark_etl_users manual__2023-07-11T21:57:11.039797+00:00 [queued]>
[2023-07-11T22:02:46.627+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-11T22:02:46.637+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_etl_users> on 2023-07-11 21:57:11.039797+00:00
[2023-07-11T22:02:46.645+0000] {standard_task_runner.py:57} INFO - Started process 1349 to run task
[2023-07-11T22:02:46.651+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_users', 'spark_etl_users', 'manual__2023-07-11T21:57:11.039797+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmppu4aw94b']
[2023-07-11T22:02:46.656+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask spark_etl_users
[2023-07-11T22:02:46.732+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_users.spark_etl_users manual__2023-07-11T21:57:11.039797+00:00 [running]> on host 5f08e8e1aa21
[2023-07-11T22:02:46.875+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Trubiano' AIRFLOW_CTX_DAG_ID='etl_users' AIRFLOW_CTX_TASK_ID='spark_etl_users' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T21:57:11.039797+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T21:57:11.039797+00:00'
[2023-07-11T22:02:46.900+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-07-11T22:02:46.901+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark /opt/***/scripts/ETL_Users.py
[2023-07-11T22:02:47.028+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-11T22:02:47.036+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64//bin/java: No such file or directory
[2023-07-11T22:02:47.038+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2023-07-11T22:02:47.078+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark /opt/***/scripts/ETL_Users.py. Error code is: 1.
[2023-07-11T22:02:47.082+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=etl_users, task_id=spark_etl_users, execution_date=20230711T215711, start_date=20230711T220246, end_date=20230711T220247
[2023-07-11T22:02:47.096+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task spark_etl_users (Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark /opt/***/scripts/ETL_Users.py. Error code is: 1.; 1349)
[2023-07-11T22:02:47.153+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T22:02:47.181+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
