[2023-07-11T02:26:55.731+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_users.spark_etl_users manual__2023-07-11T02:26:37+00:00 [queued]>
[2023-07-11T02:26:55.741+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_users.spark_etl_users manual__2023-07-11T02:26:37+00:00 [queued]>
[2023-07-11T02:26:55.742+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-07-11T02:26:55.759+0000] {taskinstance.py:1327} INFO - Executing <Task(SparkSubmitOperator): spark_etl_users> on 2023-07-11 02:26:37+00:00
[2023-07-11T02:26:55.775+0000] {standard_task_runner.py:57} INFO - Started process 2392 to run task
[2023-07-11T02:26:55.781+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_users', 'spark_etl_users', 'manual__2023-07-11T02:26:37+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/etl_users.py', '--cfg-path', '/tmp/tmptmocwglp']
[2023-07-11T02:26:55.784+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask spark_etl_users
[2023-07-11T02:26:55.945+0000] {task_command.py:410} INFO - Running <TaskInstance: etl_users.spark_etl_users manual__2023-07-11T02:26:37+00:00 [running]> on host 5f08e8e1aa21
[2023-07-11T02:26:56.255+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Trubiano' AIRFLOW_CTX_DAG_ID='etl_users' AIRFLOW_CTX_TASK_ID='spark_etl_users' AIRFLOW_CTX_EXECUTION_DATE='2023-07-11T02:26:37+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-07-11T02:26:37+00:00'
[2023-07-11T02:26:56.273+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2023-07-11T02:26:56.274+0000] {spark_submit.py:339} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/ETL_Users.py
[2023-07-11T02:26:56.601+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-07-11T02:26:56.609+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64//bin/java: No such file or directory
[2023-07-11T02:26:56.611+0000] {spark_submit.py:490} INFO - /home/***/.local/lib/python3.7/site-packages/pyspark/bin/spark-class: line 97: CMD: bad array subscript
[2023-07-11T02:26:56.648+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    f"Cannot execute: {self._mask_cmd(spark_submit_cmd)}. Error code is: {returncode}."
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/ETL_Users.py. Error code is: 1.
[2023-07-11T02:26:56.655+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=etl_users, task_id=spark_etl_users, execution_date=20230711T022637, start_date=20230711T022655, end_date=20230711T022656
[2023-07-11T02:26:56.681+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 7 for task spark_etl_users (Cannot execute: spark-submit --master spark://spark:7077 --driver-class-path /tmp/drivers/postgresql-42.5.2.jar --name arrow-spark --queue default /opt/***/scripts/ETL_Users.py. Error code is: 1.; 2392)
[2023-07-11T02:26:56.730+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-11T02:26:56.784+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
